import { auth } from "@clerk/nextjs/server";
import { redirect } from "next/navigation";
import { AdminLayout } from "@/components/AdminLayout";
import { StatsCard } from "@/components/StatsCard";
import { createServerClient } from "@/lib/supabase";
import Link from "next/link";

const ADMIN_USER_IDS = process.env.ADMIN_USER_IDS?.split(",") || [];

export default async function AdminOverviewPage() {
  const { userId } = await auth();

  if (!userId) {
    redirect("/sign-in");
  }

  // Check if user is admin
  if (!ADMIN_USER_IDS.includes(userId)) {
    redirect("/dashboard");
  }

  const supabase = createServerClient();

  // Fetch all stats
  const [
    { count: totalAffiliates },
    { count: pendingAffiliates },
    { count: approvedAffiliates },
    { data: affiliatesWithStats },
    { count: pendingReferrals },
    { count: pendingPayouts },
    { data: recentActivity },
  ] = await Promise.all([
    supabase.from("affiliates").select("*", { count: "exact", head: true }),
    supabase.from("affiliates").select("*", { count: "exact", head: true }).eq("status", "pending"),
    supabase.from("affiliates").select("*", { count: "exact", head: true }).eq("status", "approved"),
    supabase.from("affiliates").select("total_revenue, total_commission_earned, balance_owed"),
    supabase.from("referrals").select("*", { count: "exact", head: true }).eq("status", "pending"),
    supabase.from("payouts").select("*", { count: "exact", head: true }).eq("status", "pending"),
    supabase
      .from("activity_log")
      .select("*, affiliates(email, first_name, last_name)")
      .order("created_at", { ascending: false })
      .limit(10),
  ]);

  // Calculate totals
  const totalRevenue = affiliatesWithStats?.reduce((sum, a) => sum + (a.total_revenue || 0), 0) || 0;
  const totalCommission = affiliatesWithStats?.reduce((sum, a) => sum + (a.total_commission_earned || 0), 0) || 0;
  const totalOwed = affiliatesWithStats?.reduce((sum, a) => sum + (a.balance_owed || 0), 0) || 0;

  return (
    <AdminLayout>
      <div className="space-y-8">
        {/* Header */}
        <div>
          <h1 className="text-3xl font-bold text-red-500">Admin Overview</h1>
          <p className="text-gray-400 mt-1">Manage your affiliate program</p>
        </div>

        {/* Quick Actions */}
        {(pendingAffiliates || 0) > 0 && (
          <div className="bg-yellow-500/10 border border-yellow-500/30 rounded-lg p-4 flex items-center justify-between">
            <div className="flex items-center gap-3">
              <span className="text-2xl">⚠️</span>
              <div>
                <p className="text-yellow-400 font-medium">
                  {pendingAffiliates} pending affiliate application{pendingAffiliates !== 1 ? "s" : ""}
                </p>
                <p className="text-sm text-gray-400">Review and approve new affiliates</p>
              </div>
            </div>
            <Link
              href="/admin/affiliates?status=pending"
              className="px-4 py-2 bg-yellow-500 text-black rounded-lg hover:bg-yellow-400 transition-colors font-medium"
            >
              Review Now
            </Link>
          </div>
        )}

        {/* Stats Grid */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
          <StatsCard
            title="Total Affiliates"
            value={totalAffiliates || 0}
            subtitle={`${approvedAffiliates || 0} approved`}
            icon="👥"
          />
          <StatsCard
            title="Total Revenue"
            value={`$${totalRevenue.toFixed(2)}`}
            subtitle="Generated by affiliates"
            icon="📈"
          />
          <StatsCard
            title="Total Commission"
            value={`$${totalCommission.toFixed(2)}`}
            subtitle="Earned by affiliates"
            icon="💰"
          />
          <StatsCard
            title="Balance Owed"
            value={`$${totalOwed.toFixed(2)}`}
            subtitle={`${pendingPayouts || 0} pending payouts`}
            icon="🏦"
          />
        </div>

        {/* Pending Items */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
          <div className="bg-[#2c0046] border border-red-500/20 rounded-lg p-6">
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-xl font-semibold text-red-400">Pending Referrals</h2>
              <Link href="/admin/referrals?status=pending" className="text-sm text-gray-400 hover:text-red-400">
                View All →
              </Link>
            </div>
            <p className="text-4xl font-bold text-white">{pendingReferrals || 0}</p>
            <p className="text-sm text-gray-400 mt-2">Awaiting approval</p>
          </div>

          <div className="bg-[#2c0046] border border-red-500/20 rounded-lg p-6">
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-xl font-semibold text-red-400">Pending Payouts</h2>
              <Link href="/admin/payouts?status=pending" className="text-sm text-gray-400 hover:text-red-400">
                View All →
              </Link>
            </div>
            <p className="text-4xl font-bold text-white">{pendingPayouts || 0}</p>
            <p className="text-sm text-gray-400 mt-2">Ready to process</p>
          </div>
        </div>

        {/* Recent Activity */}
        <div className="bg-[#2c0046] border border-red-500/20 rounded-lg p-6">
          <div className="flex items-center justify-between mb-4">
            <h2 className="text-xl font-semibold text-red-400">Recent Activity</h2>
            <Link href="/admin/activity" className="text-sm text-gray-400 hover:text-red-400">
              View All →
            </Link>
          </div>
          <div className="space-y-3">
            {recentActivity?.map((activity) => (
              <div
                key={activity.id}
                className="flex items-center justify-between py-3 border-b border-gray-700/50 last:border-0"
              >
                <div className="flex items-center gap-3">
                  <span className="text-lg">
                    {activity.action === "signup" && "🆕"}
                    {activity.action === "approved" && "✅"}
                    {activity.action === "referral" && "🔗"}
                    {activity.action === "payout" && "💸"}
                    {activity.action === "webhook_shopify" && "🛒"}
                    {activity.action === "webhook_recharge" && "🔄"}
                    {!["signup", "approved", "referral", "payout", "webhook_shopify", "webhook_recharge"].includes(
                      activity.action
                    ) && "📝"}
                  </span>
                  <div>
                    <p className="text-white font-medium capitalize">{activity.action.replace(/_/g, " ")}</p>
                    <p className="text-sm text-gray-400">
                      {activity.affiliates
                        ? `${activity.affiliates.first_name || ""} ${activity.affiliates.last_name || ""} (${activity.affiliates.email})`.trim()
                        : "System"}
                    </p>
                  </div>
                </div>
                <p className="text-sm text-gray-500">
                  {new Date(activity.created_at).toLocaleDateString("en-US", {
                    month: "short",
                    day: "numeric",
                    hour: "2-digit",
                    minute: "2-digit",
                  })}
                </p>
              </div>
            ))}
            {(!recentActivity || recentActivity.length === 0) && (
              <p className="text-gray-500 text-center py-4">No recent activity</p>
            )}
          </div>
        </div>
      </div>
    </AdminLayout>
  );
}
